//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeinSportTable.Sport {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Data", Namespace="http://schemas.datacontract.org/2004/07/WcfLiblary")]
    [System.SerializableAttribute()]
    public partial class Data : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssotiationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrainersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double j1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double j2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double j3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double p1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double p2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double p3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double t1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double t2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double t3Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Assotiation {
            get {
                return this.AssotiationField;
            }
            set {
                if ((object.ReferenceEquals(this.AssotiationField, value) != true)) {
                    this.AssotiationField = value;
                    this.RaisePropertyChanged("Assotiation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Birthday {
            get {
                return this.BirthdayField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthdayField, value) != true)) {
                    this.BirthdayField = value;
                    this.RaisePropertyChanged("Birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Club {
            get {
                return this.ClubField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubField, value) != true)) {
                    this.ClubField = value;
                    this.RaisePropertyChanged("Club");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Level {
            get {
                return this.LevelField;
            }
            set {
                if ((object.ReferenceEquals(this.LevelField, value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sity {
            get {
                return this.SityField;
            }
            set {
                if ((object.ReferenceEquals(this.SityField, value) != true)) {
                    this.SityField = value;
                    this.RaisePropertyChanged("Sity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Trainers {
            get {
                return this.TrainersField;
            }
            set {
                if ((object.ReferenceEquals(this.TrainersField, value) != true)) {
                    this.TrainersField = value;
                    this.RaisePropertyChanged("Trainers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((object.ReferenceEquals(this.WeightField, value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double j1 {
            get {
                return this.j1Field;
            }
            set {
                if ((this.j1Field.Equals(value) != true)) {
                    this.j1Field = value;
                    this.RaisePropertyChanged("j1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double j2 {
            get {
                return this.j2Field;
            }
            set {
                if ((this.j2Field.Equals(value) != true)) {
                    this.j2Field = value;
                    this.RaisePropertyChanged("j2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double j3 {
            get {
                return this.j3Field;
            }
            set {
                if ((this.j3Field.Equals(value) != true)) {
                    this.j3Field = value;
                    this.RaisePropertyChanged("j3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double p1 {
            get {
                return this.p1Field;
            }
            set {
                if ((this.p1Field.Equals(value) != true)) {
                    this.p1Field = value;
                    this.RaisePropertyChanged("p1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double p2 {
            get {
                return this.p2Field;
            }
            set {
                if ((this.p2Field.Equals(value) != true)) {
                    this.p2Field = value;
                    this.RaisePropertyChanged("p2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double p3 {
            get {
                return this.p3Field;
            }
            set {
                if ((this.p3Field.Equals(value) != true)) {
                    this.p3Field = value;
                    this.RaisePropertyChanged("p3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double t1 {
            get {
                return this.t1Field;
            }
            set {
                if ((this.t1Field.Equals(value) != true)) {
                    this.t1Field = value;
                    this.RaisePropertyChanged("t1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double t2 {
            get {
                return this.t2Field;
            }
            set {
                if ((this.t2Field.Equals(value) != true)) {
                    this.t2Field = value;
                    this.RaisePropertyChanged("t2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double t3 {
            get {
                return this.t3Field;
            }
            set {
                if ((this.t3Field.Equals(value) != true)) {
                    this.t3Field = value;
                    this.RaisePropertyChanged("t3");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Sport.ISportService")]
    public interface ISportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISportService/SetData", ReplyAction="http://tempuri.org/ISportService/SetDataResponse")]
        void SetData(SeinSportTable.Sport.Data value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISportService/SetData", ReplyAction="http://tempuri.org/ISportService/SetDataResponse")]
        System.Threading.Tasks.Task SetDataAsync(SeinSportTable.Sport.Data value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISportServiceChannel : SeinSportTable.Sport.ISportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SportServiceClient : System.ServiceModel.ClientBase<SeinSportTable.Sport.ISportService>, SeinSportTable.Sport.ISportService {
        
        public SportServiceClient() {
        }
        
        public SportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SetData(SeinSportTable.Sport.Data value) {
            base.Channel.SetData(value);
        }
        
        public System.Threading.Tasks.Task SetDataAsync(SeinSportTable.Sport.Data value) {
            return base.Channel.SetDataAsync(value);
        }
    }
}
